version: "3.3"
services:
  database:
    image: postgres:latest # use latest official postgres version
    container_name: supplier_management_pg
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - 5432:5432
    volumes:
      - ./battlefield.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10

  redis:
    image: redis:latest
    container_name: supplier_management_redis
    ports:
      - 6379:6379

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: supplier_management_api
    ports: 
      - 2020:2020
    depends_on: 
      - database
      - redis
    volumes: 
      - ./.env:/dist/.env